### ISSUE TITLE
启动Galay.order.api项目 调用/api/app/order/{id}接口的时候报错

### ISSUE THREAD

**Issue by 312527814** [jessetalk/Galaxy#8]
![image](https://user-images.githubusercontent.com/22831482/87759165-653a4080-c840-11ea-83aa-4172161bd658.png)
启动Galay.order.api 调用/api/app/order/{id}这个接口的时候报错，这啥原因啊，用的是 abp分支

**Comment by jessetalk** [comment]
是不是product.api没有启动？ 这个api会调用product.api

**Comment by 312527814** [comment]
product.api也已经启动了
![Uploading image.png…]()

**Comment by 312527814** [comment]
product.api也已经启动
![image](https://user-images.githubusercontent.com/22831482/88021061-654b8080-cb5f-11ea-8ee5-02fab7183d37.png)

**Comment by Lingpeng-Jiang** [comment]
> ![image](https://user-images.githubusercontent.com/22831482/87759165-653a4080-c840-11ea-83aa-4172161bd658.png)
> 启动Galay.order.api 调用/api/app/order/{id}这个接口的时候报错，这啥原因啊，用的是 abp分支

需要在GalaxyOrderWebModule上注册模块[DependsOn(typeof(AbpHttpClientModule))]，但是会有新的问题，提示找不到【ProductStore】

**Comment by Lingpeng-Jiang** [comment]
> ![image](https://user-images.githubusercontent.com/22831482/87759165-653a4080-c840-11ea-83aa-4172161bd658.png)
> 启动Galay.order.api 调用/api/app/order/{id}这个接口的时候报错，这啥原因啊，用的是 abp分支

还要注册模块 [DependsOn(typeof(GalaxyProductContractModule))]，但是的，我的电脑上出现SSL无法访问，不清楚要怎么解决了

**Comment by YahuiWong** [comment]
同样遇到了这个问题

**Comment by YahuiWong** [comment]
我发现是appsettings.Development.json没有生效--！我明明是Development模式的 把配置写到 appsettings.json 就能正常调用了

**Comment by 312527814** [comment]
> 我发现是appsettings.Development.json没有生效--！我明明是Development模式的 把配置写到 appsettings.json 就能正常调用了

把你的源码发出来呗，我这把配置写到 appsettings.json  也不行呢  也是出现SSL无法访问的现象

**Comment by YahuiWong** [comment]
> > 我发现是appsettings.Development.json没有生效--！我明明是Development模式的 把配置写到 appsettings.json 就能正常调用了
> 
> 把你的源码发出来呗，我这把配置写到 appsettings.json 也不行呢 也是出现SSL无法访问的现象

你这种情况 建议 直接修改 Galaxy.Order.Api 和 Galaxy.Product.API 为http的启动 然后修改 appsettings.json的 RemoteServices的BaseUrl成http的 有的是个人电脑的问题 https无法使用

**Comment by 312527814** [comment]
> > > 我发现是appsettings.Development.json没有生效--！我明明是Development模式的 把配置写到 appsettings.json 就能正常调用了
> > 
> > 
> > 把你的源码发出来呗，我这把配置写到 appsettings.json 也不行呢 也是出现SSL无法访问的现象
> 
> 你这种情况 建议 直接修改 Galaxy.Order.Api 和 Galaxy.Product.API 为http的启动 然后修改 appsettings.json的 RemoteServices的BaseUrl成http的 有的是个人电脑的问题 https无法使用

哎呀 眼拙 没看见 BaseUrl 是https的，经过实验最终成功.
总结：
1 需要在GalaxyOrderWebModule 上注册模块[DependsOn(typeof(AbpHttpClientModule))] 
2 把配置写到 appsettings.json
3 如果只支持http 需要修改 Galaxy.Order.Api 和 Galaxy.Product.API 为http的启动，BaseUrl改为http协议。
